"use strict";

module.exports = {
  authController: require("./auth"),
  schoolController: require("./school"),
  userController: require("./user"),
  sessionController: require("./session"),
  classController: require("./class"),
  subjectController: require("./subject"),
  teacherController: require("./teacher"),
  studentController: require("./student"),
  parentController: require("./parent"),
  applicationController: require("./application"),
  attendanceController: require("./attendance"),
  feeController: require("./fee"),
  examController: require("./exam"),
  timetableController: require("./timetable"),
  teacherAbsenceController: require("./teacher_absence"),
  dailyLessonController: require("./daily_lesson"),
  dailyTestController: require("./daily_test"),
  plannedChapterController: require("./planned_chapter"),
  settingsController: require("./settings"),
  auditController: require("./audit"),
  expenseController: require("./expense"),
  noticeController: require("./notice"),
  leaveController: require("./leave"),
  reportController: require("./report"),
};
