"use strict";

module.exports = {
  authService: require("./auth.service"),
  userService: require("./user.service"),
  schoolService: require("./school.service"),
  sessionService: require("./session.service"),
  classService: require("./class.service"),
  subjectService: require("./subject.service"),
  teacherService: require("./teacher.service"),
  studentService: require("./student.service"),
  parentService: require("./parent.service"),
  applicationService: require("./application.service"),
  attendanceService: require("./attendance.service"),
  feeService: require("./fee.service"),
  examService: require("./exam.service"),
  timetableService: require("./timetable.service"),
  auditService: require("./audit.service"),
  teacherAbsenceService: require("./teacher_absence.service"),
  dailyLessonService: require("./daily_lesson.service"),
  dailyTestService: require("./daily_test.service"),
  plannedChapterService: require("./planned_chapter.service"),
  settingsService: require("./settings.service"),
  accessService: require("./access.service"),
  expenseService: require("./expense.service"),
  noticeService: require("./notice.service"),
  emailService: require("./email.service"),
};
